name = "xray"
main = "build/worker/index.js"
compatibility_date = "2024-05-23"
minify = true

account_id = "c94c08c1fa3eb249700c89571fc3a332"
workers_dev = true

[[kv_namespaces]]
binding = "YUMI"
id = "4bf5f900d3034fd3ba03ee4c23aa2f8d"

[build]

command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "2bcfbfba-b446-4ad5-93ad-72af9e008f61"
