name = "xray"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true


account_id = "a434665e08ee73300928200f5432f4a4"
workers_dev = true

[[kv_namespaces]]
binding = "YUMI"
id = "647287d362c74a3a880543cb36e03b7e"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "2bcfbfba-b446-4ad5-93ad-72af9e008f61"
